apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app-deployment
  template:
    metadata:
      labels:
        app: django-app-deployment
    spec:
      containers:
        - name: django-app
          image: djangoregistry.azurecr.io/django-k8s:latest
          envFrom:
            - secretRef:
                name: django-k8s-prod-env
          env:
            - name: PORT
              value: "8182"
          ports:
            - containerPort: 8182
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"  
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata: 
  name: django-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8182 #trebuie sa fie la fel cu value lui PORT din env
  selector: 
    app: django-app-deployment

